sed -i 's/${language && language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all your analysis and content STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}. Do not use English unless it is for technical terms that have no direct translation.` : '\'''\''}/${language \&\& language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all your analysis and content STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}. Do not use English unless it is for technical terms that have no direct translation.` : `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all your analysis and content STRICTLY in English. Do NOT output in Hindi, Gujarati, or any other regional language.`}/g' server.ts

sed -i 's/${language && language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all content STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}.` : '\'''\''}/${language \&\& language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all content STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}.` : `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST output all content STRICTLY in English.`}/g' server.ts

sed -i 's/${language && language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST answer the user STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}.` : '\'''\''}/${language \&\& language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST answer the user STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}.` : `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST answer the user STRICTLY in English.`}/g' server.ts

sed -i 's/${language && language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST draft the document STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}, unless the user asks otherwise.` : '\'''\''}/${language \&\& language !== '\''en'\'' ? `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST draft the document STRICTLY in ${language === '\''hi'\'' ? '\''Hindi'\'' : language === '\''gu'\'' ? '\''Gujarati'\'' : language}, unless the user asks otherwise.` : `\\nCRITICAL LANGUAGE REQUIREMENT: You MUST draft the document STRICTLY in English, unless the user asks otherwise.`}/g' server.ts

sed -i 's/Translate complex terms into Gujarati\/Hindi-influenced professional plain English that a local businessman easily understands./Translate complex terms into professional plain English that a local businessman easily understands./g' server.ts

