import type { BOQType, BOQTypeConfidence } from './types';

export interface BoqTypeDetectionResult {
  type: BOQType;
  confidence: BOQTypeConfidence;
  score: number;    // 0–100 for UX badge ("✓ Auto-detected (92%)")
  reason: string;   // decision log — WHY this type was chosen
}

// Pattern categories: signals must come from ≥2 distinct categories for non-trivial confidence.
// This prevents co-firing patterns (e.g. "5% above the estimated amount" matching both
// bid_wording AND estimated_ref) from counting as 2 independent high-confidence signals.
type PatternCategory = 'bid_form' | 'bid_wording' | 'estimated_ref' | 'type_label';

interface CategorizedPattern {
  category: PatternCategory;
  re: RegExp;
  label: string;
}

// Ordered from most specific to most general within each category.
const PERCENTAGE_RATE_PATTERNS: CategorizedPattern[] = [
  // bid_form — verbatim boilerplate unique to percentage-rate financial bid forms;
  //   never generated by AI summaries or found in general conditions headings.
  { category: 'bid_form', re: /willing\s+to\s+carry\s+out(?:\s+the\s+work)?/i,            label: 'willing to carry out the work' },
  { category: 'bid_form', re: /quote\s+(?:a\s+)?percentage\s+(?:above|below)/i,            label: 'quote a percentage above/below' },
  { category: 'bid_form', re: /rate\s+@\s*[\d.]*\s*%\s*(?:above|below)/i,                 label: 'rate @__% above/below' },

  // bid_wording — the explicit above/below bid-direction sentence with a percentage.
  { category: 'bid_wording', re: /\d[\d,.]*\s*%\s*(?:above|below)\s+(?:the\s+)?(?:estimated|tendered|scheduled)/i, label: '__% above/below the estimated amount' },
  { category: 'bid_wording', re: /above\s*[/|&]\s*below\s+(?:the\s+)?(?:estimated|tendered)/i,                     label: 'above / below the estimated' },
  { category: 'bid_wording', re: /(?:add|deduct)\s+[\d.]+\s*%/i,                                                   label: 'add/deduct __% ' },

  // estimated_ref — references to a pre-set estimated rate or amount.
  { category: 'estimated_ref', re: /of\s+the\s+estimated\s+(?:rate|amount|cost)/i,                                  label: 'of the estimated rate/amount' },
  { category: 'estimated_ref', re: /(?:above|below)\s+the\s+(?:estimated|scheduled)\s+(?:amount|cost|rate)/i,       label: 'above/below the estimated amount/rate' },

  // type_label — generic labels; can appear verbatim in AI-generated summaries or in negative
  //   context ("this is not a percentage tender"); weakest signal — never triggers auto-select.
  { category: 'type_label', re: /percentage\s+tender\b/i, label: 'percentage tender' },
  { category: 'type_label', re: /percentage\s+rate/i,     label: 'percentage rate' },
  { category: 'type_label', re: /\bsor\s+rate/i,          label: 'SOR rate' },
  { category: 'type_label', re: /\bdsr\s+rate/i,          label: 'DSR rate' },
];

const ITEM_RATE_PATTERNS: CategorizedPattern[] = [
  { category: 'bid_form', re: /\bitem\s+rate\s+(?:tender|contract|bid)\b/i,                              label: 'item rate tender/contract' },
  { category: 'bid_form', re: /quote\s+(?:your\s+)?(?:unit\s+)?rates?\s+for\s+(?:each|the\s+following)/i, label: 'quote your unit rates for each item' },
  { category: 'bid_form', re: /(?:fill\s+in|enter|insert)\s+(?:your\s+)?(?:unit\s+)?rates?/i,            label: 'fill in your unit rates' },
];

function buildCategoryHits(
  text: string,
  patterns: CategorizedPattern[],
): Map<PatternCategory, string[]> {
  const hits = new Map<PatternCategory, string[]>();
  for (const p of patterns) {
    if (p.re.test(text)) {
      const list = hits.get(p.category) ?? [];
      list.push(p.label);
      hits.set(p.category, list);
    }
  }
  return hits;
}

function formatReason(
  typeLabel: string,
  confidence: BOQTypeConfidence,
  hits: Map<PatternCategory, string[]>,
): string {
  const parts: string[] = [];
  for (const [cat, excerpts] of hits) {
    parts.push(`${cat}("${excerpts[0]}")`);
  }
  return parts.length
    ? `${typeLabel} [${confidence}]: ${parts.join(', ')}`
    : `${typeLabel} [${confidence}]: no indicators`;
}

export function detectBoqTypeFromText(text: string): BoqTypeDetectionResult {
  if (!text?.trim()) {
    return { type: 'unknown', confidence: 'low', score: 0, reason: 'No text provided' };
  }

  const hits = buildCategoryHits(text, PERCENTAGE_RATE_PATTERNS);
  const hasBidForm  = hits.has('bid_form');
  const hasBidWord  = hits.has('bid_wording');
  const hasEstRef   = hits.has('estimated_ref');
  const hasLabel    = hits.has('type_label');
  const strongCount = [hasBidForm, hasBidWord, hasEstRef].filter(Boolean).length;

  // HIGH: bid_form boilerplate + at least one corroborating strong signal
  if (hasBidForm && strongCount >= 2) {
    const score = Math.min(98, 85 + 4 * (strongCount - 1));
    return { type: 'percentage_rate', confidence: 'high', score, reason: formatReason('Percentage Rate', 'high', hits) };
  }

  // MEDIUM: bid_wording + estimated_ref, but no verified bid-form boilerplate
  if (!hasBidForm && hasBidWord && hasEstRef) {
    return { type: 'percentage_rate', confidence: 'medium', score: 60, reason: formatReason('Percentage Rate', 'medium', hits) };
  }

  // MEDIUM: bid_form phrase found but no numeric direction — boilerplate alone, weak
  if (hasBidForm) {
    return { type: 'percentage_rate', confidence: 'medium', score: 50, reason: formatReason('Percentage Rate', 'medium', hits) };
  }

  // LOW: a single strong signal without corroboration
  if (hasBidWord || hasEstRef) {
    return { type: 'percentage_rate', confidence: 'low', score: 28, reason: formatReason('Percentage Rate', 'low', hits) };
  }

  // LOW: generic type label only — present in AI text; never auto-select
  if (hasLabel) {
    return { type: 'percentage_rate', confidence: 'low', score: 18, reason: formatReason('Percentage Rate', 'low', hits) };
  }

  // Item rate detection — only checked when NO percentage-rate signals found
  const itemHits = buildCategoryHits(text, ITEM_RATE_PATTERNS);
  if (itemHits.size > 0) {
    const score = itemHits.size >= 2 ? 62 : 42;
    const conf: BOQTypeConfidence = itemHits.size >= 2 ? 'medium' : 'low';
    return { type: 'item_rate', confidence: conf, score, reason: formatReason('Item Rate', conf, itemHits) };
  }

  return { type: 'unknown', confidence: 'low', score: 0, reason: 'No BOQ type indicators found in document text' };
}

/** AI-summarized text fields most likely to describe the tender's nature —
 *  not the raw document, so exact phrases (e.g. a document title) aren't
 *  guaranteed to survive, but defining characteristics usually do. Shared
 *  by detectBoqTypeFromAnalysis and the Rate Contract hint (detectRateContract.ts). */
export function extractAnalysisText(analysisResult: unknown): string {
  if (!analysisResult || typeof analysisResult !== 'object') return '';
  const r = analysisResult as Record<string, unknown>;
  const str = (v: unknown): string => (typeof v === 'string' ? v : '');
  const ts = r['tender_simplified'] as Record<string, unknown> | undefined;
  const br = r['bid_recommendation'] as Record<string, unknown> | undefined;
  return [
    str(ts?.['scope_of_work']),
    str(br?.['rationale']),
    str(br?.['estimated_value']),
  ].filter(Boolean).join(' ');
}

/** Parses bid_recommendation.estimated_value (a free-text AI string, e.g.
 *  "₹25,00,000") into a number, or null if absent/unparseable. */
export function extractBidRecommendationEstimatedValue(analysisResult: unknown): number | null {
  if (!analysisResult || typeof analysisResult !== 'object') return null;
  const r = analysisResult as Record<string, unknown>;
  const br = r['bid_recommendation'] as Record<string, unknown> | undefined;
  const raw = br?.['estimated_value'];
  if (typeof raw !== 'string') return null;
  const n = parseFloat(raw.replace(/[^0-9.]/g, ''));
  return isFinite(n) && n > 0 ? n : null;
}

// Scans AI-generated analysis fields for BOQ type hints.
// HARD CAP: output confidence is always 'low' — AI text fields must NEVER trigger auto-selection.
// Only used as a last-resort display hint, not for state mutation.
export function detectBoqTypeFromAnalysis(analysisResult: unknown): BoqTypeDetectionResult {
  if (!analysisResult || typeof analysisResult !== 'object') {
    return { type: 'unknown', confidence: 'low', score: 0, reason: 'No analysis result' };
  }

  const combined = extractAnalysisText(analysisResult);
  const raw = detectBoqTypeFromText(combined);
  return {
    type: raw.type,
    confidence: 'low',
    score: Math.min(raw.score, 25),
    reason: `AI text fields (capped low — not a primary signal): ${raw.reason}`,
  };
}

// Phase 2 structural detection (Priority 1): inspects pre-filled estimated rates.
// In percentage-rate tenders the authority pre-fills all item rates;
// in item-rate tenders the rate column is empty (bidder fills in rates).
export function detectBoqTypeFromItems(
  items: { estimatedRate?: number; quantity?: number }[],
): BoqTypeDetectionResult {
  if (!items.length) {
    return { type: 'unknown', confidence: 'low', score: 0, reason: 'No BOQ items to analyze structurally' };
  }

  const withRate = items.filter(i => i.estimatedRate != null && i.estimatedRate > 0).length;
  const withQty  = items.filter(i => i.quantity != null && i.quantity > 0).length;
  const fillRatio = withRate / items.length;

  if (items.length >= 3 && fillRatio >= 0.8) {
    return {
      type: 'percentage_rate',
      confidence: 'high',
      score: 92,
      reason: `Structural: ${withRate}/${items.length} BOQ items have pre-filled estimated rates — authority provided rates (Percentage Rate pattern)`,
    };
  }

  if (items.length >= 3 && fillRatio <= 0.1 && withQty >= items.length * 0.7) {
    return {
      type: 'item_rate',
      confidence: 'high',
      score: 88,
      reason: `Structural: ${items.length - withRate}/${items.length} BOQ items have empty rate column with quantities — bidder fills rates (Item Rate pattern)`,
    };
  }

  return {
    type: 'unknown',
    confidence: 'low',
    score: 0,
    reason: `Structural: mixed rate fill (${Math.round(fillRatio * 100)}% pre-filled across ${items.length} items) — insufficient evidence`,
  };
}
